### ISSUE TITLE
Finish readme.md

### ISSUE THREAD

**Issue by AkselOldeide** [JNettli/010-BarcodeAllergenScanner#33]
[Readme.md](https://github.com/JNettli/010-BarcodeAllergenScanner/blob/main/README.md) Needs to contain all nescessary info, including: Design link, intructions of use, live deploy, tools utilized ++

**Comment by ChristianWestby** [comment]
I have written a ReadMe. Please comment .

**Comment by AkselOldeide** [comment]
Complete
